name: Stock Market Alerts Cron

on:
  schedule:
    - cron: 40 7 * * 1-5 #3:40am start Monday to Friday for pre-market hours at 4am because github actions are trash at starting on time.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies # This step only runs if requirements.txt dependencies change
        run: |
          pip install -r requirements.txt
      - name: Print safe config secrets without masking to verify settings
        env:
          ACTIONS_STEP_DEBUG: true
        run: |
          echo "::set-output ${{ secrets.stock_symbols }}"
          echo "::set-output ${{ secrets.percent_change_threshold }}"
          echo "::set-output ${{ secrets.sender_email }}"
          echo "::set-output ${{ secrets.sender_email_host }}"
          echo "::set-output ${{ secrets.sender_email_host_port }}"
          echo "::set-output ${{ secrets.carrier }}"
      - name: Run script
        run: |
          echo "Script launching!"
          python -u main.py --stock_symbols ${{ secrets.stock_symbols }} --percent_change_threshold ${{ secrets.percent_change_threshold }} --sender_email ${{ secrets.sender_email }} --sender_email_host ${{ secrets.sender_email_host }} --sender_email_host_port ${{ secrets.sender_email_host_port }} --sender_email_password ${{ secrets.sender_email_password }} --carrier ${{ secrets.carrier }} --phone_numbers ${{ secrets.phone_numbers }} --yahoo_api_key ${{ secrets.yahoo_api_key }}
        timeout-minutes: 355
        continue-on-error: true # Mark a success even though timeout so action gets marked as success and pip cache can be built(won't be built if job is failed)
      - name: Restart after timed out
        run: |
          TZ='America/New_York' # Set timezone to EST
          if [ "$(date +%H)" -ge 20 ]; then # Check if hour is 20 (8pm EST) or later
            echo "Past post market hours, exiting github action loop"
            exit 0
          fi
          echo "Restarting workflow..."
          curl -X POST \
          https://api.github.com/repos/jeremyjpj0916/stock-market-alerts/actions/workflows/cron.yml/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H 'Authorization: Bearer ${{ secrets.HUB_PAT }}' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"ref":"main"}'
