name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          stock_symbols: ${{ secrets.STOCK_SYMBOLS }}
          percent_change_threshold: ${{ secrets.PERCENT_CHANGE_THRESHOLD }}

      - name: Build and push image
        run: |
          docker build -t stock-market-alerts .
          docker tag stock-market-alerts:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stock-market-alerts:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stock-market-alerts:latest

      - name: Update ECS task definition
        run: |
          aws ecs update-task-definition --cluster stock-market-alerts --task-definition stock-market-alerts --container-definitions file://container-definitions.json
