name: Deploy to AWS

on:
  #push:
    #branches:
     # - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          stock_symbols: ${{ secrets.STOCK_SYMBOLS }}
          percent_change_threshold: ${{ secrets.PERCENT_CHANGE_THRESHOLD }}

      - name: Build and push image
        run: |
          docker build -t stock-market-alerts .
          docker tag stock-market-alerts:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stock-market-alerts:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stock-market-alerts:latest

      - name: Update ECS task definition
        run: |
          aws ecs update-task-definition --cluster stock-market-alerts --task-definition stock-market-alerts --container-definitions file://container-definitions.json
